stages:
  - publish

npm_publish:
  stage: publish
  only:
    - tags
  image: node:20
  script:
    # Ensure the git tag matches the npm package version (e.g. tag v1.0.0 for version 1.0.0)
    - test -n "${NPM_AUTH_TOKEN}" && echo 'NPM_AUTH_TOKEN is available' || echo 'NPM_AUTH_TOKEN is not available (not set or this branch/tag has insufficient permissions)'
    - PKG_NAME=$(node -e 'console.log(JSON.parse(fs.readFileSync("package.json")).name)')
    - PKG_VERSION=$(node -e 'console.log(JSON.parse(fs.readFileSync("package.json")).version)')
    - echo 'Package name:' $PKG_NAME
    - echo 'Package version:' $PKG_VERSION
    - echo 'Tag:' $CI_COMMIT_TAG
    - test "$CI_COMMIT_TAG" = "v$PKG_VERSION"
